"""Playbooks — the action attached to every signal.

The brief asks for "ideally, what action should be taken when usage drops". A
score that only colours a row red pushes that work back onto the person it was
meant to relieve, so every signal here carries an owner, a channel, an SLA, the
concrete steps, and a WhatsApp draft in the register Raimundo already uses with
residence directors.

WhatsApp is the default channel on purpose: it is the channel that already
works for this company. The product should industrialise the habit, not replace it.
"""

from __future__ import annotations

PLAYBOOKS = {
    "reactivar_uso": {
        "title_es": "Reactivar uso antes de que se normalice",
        "title_en": "Re-activate usage before it becomes the new normal",
        "objective_es": "Entender la causa de la caída y recuperar el ritmo de registro en dos semanas.",
        "objective_en": "Understand the cause of the drop and restore recording rhythm within two weeks.",
        "owner": "csm",
        "channel": "whatsapp",
        "sla_days": 3,
        "steps_es": [
            "Revisar qué módulo concentra la caída antes de escribir.",
            "Mensaje por WhatsApp al contacto principal, sin tono de auditoría.",
            "Ofrecer 20 min de videollamada con el equipo de turno.",
            "Si hubo cambio de personal, agendar capacitación breve.",
            "Volver a medir a los 14 días y cerrar o escalar.",
        ],
        "steps_en": [
            "Identify which module the drop is concentrated in before writing.",
            "WhatsApp the main contact - not in an audit tone.",
            "Offer a 20-minute call with the shift team.",
            "If staff changed, schedule a short training session.",
            "Re-measure at 14 days, then close or escalate.",
        ],
        "whatsapp_es": "Hola {contact}, ¿cómo estás? Vi que este último mes bajó un poco el registro en {module} en {residence}. ¿Pasó algo con el equipo o hay algo de la plataforma que les está complicando? Si quieren les damos una mano, sin problema.",
        "whatsapp_en": "Hi {contact}, how are you? I noticed recording in {module} dropped a bit at {residence} this past month. Did something change with the team, or is something in the platform getting in the way? Happy to help if useful.",
        "expected_es": "Recuperar al menos el 80% del volumen previo en 14 días.",
        "expected_en": "Recover at least 80% of prior volume within 14 days.",
    },
    "recuperar_modulo": {
        "title_es": "Recuperar un módulo abandonado",
        "title_en": "Win back an abandoned module",
        "objective_es": "Volver a poner en uso un módulo contratado que dejó de registrarse.",
        "objective_en": "Bring a contracted module that went silent back into use.",
        "owner": "csm",
        "channel": "whatsapp",
        "sla_days": 5,
        "steps_es": [
            "Confirmar si dejaron de usarlo o cambiaron de proceso.",
            "Detectar si el flujo se rompió por un cambio de personal.",
            "Mostrar el módulo en 10 minutos con datos reales de su residencia.",
            "Dejar un responsable nombrado dentro del equipo.",
        ],
        "steps_en": [
            "Confirm whether they stopped using it or changed process.",
            "Check whether a staffing change broke the workflow.",
            "Walk the module in 10 minutes using their own data.",
            "Leave a named owner inside their team.",
        ],
        "whatsapp_es": "Hola {contact}, una consulta corta: veo que {module} no se está usando hace {days} días en {residence}. ¿Lo dejaron de lado o cambiaron la forma de registrarlo? Si les sirve te muestro en 10 minutos cómo lo están usando otras residencias parecidas.",
        "whatsapp_en": "Hi {contact}, quick question: I can see {module} hasn't been used for {days} days at {residence}. Did you set it aside, or change how you record it? Happy to show you in 10 minutes how similar residences are using it.",
        "expected_es": "Módulo con registro sostenido durante 3 semanas seguidas.",
        "expected_en": "Module recording sustained for 3 consecutive weeks.",
    },
    "ampliar_base_usuarios": {
        "title_es": "Ampliar la base de usuarios",
        "title_en": "Widen the user base",
        "objective_es": "Reducir la dependencia de una sola persona dentro de la residencia.",
        "objective_en": "Reduce dependence on a single person inside the residence.",
        "owner": "csm",
        "channel": "llamada",
        "sla_days": 7,
        "steps_es": [
            "Identificar qué roles deberían estar registrando y no lo hacen.",
            "Proponer una capacitación de 30 min por turno.",
            "Activar las licencias que están sin usar.",
            "Acordar que el checklist lo cierre cada TENS en su turno.",
        ],
        "steps_en": [
            "Identify which roles should be recording and are not.",
            "Propose a 30-minute training per shift.",
            "Activate the licences sitting unused.",
            "Agree that each nursing technician closes their own shift checklist.",
        ],
        "whatsapp_es": "Hola {contact}, veo que casi todo el registro de {residence} lo está haciendo {user}. Es un riesgo si esa persona se va de vacaciones o cambia de trabajo. ¿Te parece si capacitamos al resto del equipo? Son 30 minutos por turno y quedan todos cubiertos.",
        "whatsapp_en": "Hi {contact}, I can see almost all recording at {residence} is being done by {user}. That's a risk if they take holiday or move on. Shall we train the rest of the team? It's 30 minutes per shift and covers everyone.",
        "expected_es": "Al menos 3 usuarios activos y ningún usuario sobre el 50% del registro.",
        "expected_en": "At least 3 active users and no single user above 50% of recording.",
    },
    "cerrar_brecha_clinica": {
        "title_es": "Cerrar brecha de registro clínico",
        "title_en": "Close the clinical recording gap",
        "objective_es": "Dejar la residencia en condiciones de enfrentar una fiscalización SEREMI/SENAMA.",
        "objective_en": "Leave the residence ready for a SEREMI/SENAMA inspection.",
        "owner": "csm",
        "channel": "llamada",
        "sla_days": 2,
        "steps_es": [
            "Listar los días sin registro en módulos clínicos del último mes.",
            "Llamar a la enfermera jefe, no al área administrativa.",
            "Revisar si el problema es de tablets, turnos o formación.",
            "Configurar recordatorio de cierre de turno.",
        ],
        "steps_en": [
            "List the days with no clinical recording in the last month.",
            "Call the head nurse, not the administrative team.",
            "Check whether the blocker is tablets, shifts or training.",
            "Configure a shift-close reminder.",
        ],
        "whatsapp_es": "Hola {contact}, te escribo por algo que conviene mirar: en el último mes quedaron {days} días sin registro en {module} en {residence}. Ante una fiscalización eso se nota. ¿Vemos qué está pasando con los turnos? Podemos dejarlo ordenado esta semana.",
        "whatsapp_en": "Hi {contact}, flagging something worth a look: over the last month {residence} had {days} days with no {module} entry. That shows up in an inspection. Can we look at what's happening with the shifts? We can have it tidy this week.",
        "expected_es": "Cero días sin registro clínico en las 4 semanas siguientes.",
        "expected_en": "Zero days without clinical recording over the next 4 weeks.",
    },
    "activar_apoderados": {
        "title_es": "Activar el Portal de Apoderados",
        "title_en": "Activate the Family Portal",
        "objective_es": "Poner en uso el módulo que más percibe la familia del residente.",
        "objective_en": "Put into use the module the resident's family actually sees.",
        "owner": "csm",
        "channel": "whatsapp",
        "sla_days": 10,
        "steps_es": [
            "Confirmar cuántos apoderados tienen acceso creado.",
            "Proponer activar 10 familias piloto.",
            "Entregar el texto de invitación listo para enviar.",
            "Medir accesos a las 3 semanas.",
        ],
        "steps_en": [
            "Confirm how many family members have access created.",
            "Propose activating 10 pilot families.",
            "Hand over ready-to-send invitation copy.",
            "Measure logins at 3 weeks.",
        ],
        "whatsapp_es": "Hola {contact}, el Portal de Apoderados de {residence} está contratado pero casi sin uso. Es lo que más valoran las familias y baja mucho las llamadas a recepción. ¿Partimos activando 10 familias esta semana? Yo te paso el texto de invitación listo.",
        "whatsapp_en": "Hi {contact}, the Family Portal at {residence} is contracted but barely used. It's what families value most and it cuts calls to reception a lot. Shall we start by activating 10 families this week? I'll send you the invitation copy ready to go.",
        "expected_es": "10 apoderados activos y accesos sostenidos por 3 semanas.",
        "expected_en": "10 active family users with sustained logins for 3 weeks.",
    },
    "acompanar_onboarding": {
        "title_es": "Acompañar onboarding",
        "title_en": "Support onboarding",
        "objective_es": "Llegar al uso esperado antes de los 90 días de contrato.",
        "objective_en": "Reach expected usage before day 90 of the contract.",
        "owner": "onboarding",
        "channel": "visita",
        "sla_days": 5,
        "steps_es": [
            "Revisar qué módulos aún no se han tocado.",
            "Agendar visita o videollamada con los tres turnos.",
            "Fijar meta de uso semanal con la dirección.",
            "Revisar avance cada semana durante un mes.",
        ],
        "steps_en": [
            "Review which modules have not been touched yet.",
            "Book a visit or call covering all three shifts.",
            "Agree a weekly usage target with the director.",
            "Review progress weekly for a month.",
        ],
        "whatsapp_es": "Hola {contact}, ya llevamos {days} días desde la puesta en marcha en {residence}. Vamos bien, pero quedan módulos sin estrenar. ¿Coordinamos una visita para dejar los tres turnos andando? Con eso quedan al 100%.",
        "whatsapp_en": "Hi {contact}, we're {days} days into go-live at {residence}. Good progress, but some modules haven't been touched yet. Shall we book a visit to get all three shifts running? That gets you to 100%.",
        "expected_es": "Todos los módulos contratados con uso real antes del día 90.",
        "expected_en": "Every contracted module in real use before day 90.",
    },
    "resolver_friccion": {
        "title_es": "Resolver fricción de producto",
        "title_en": "Resolve product friction",
        "objective_es": "Sacar del camino el problema que está frenando el uso.",
        "objective_en": "Remove the blocker that is holding usage back.",
        "owner": "soporte",
        "channel": "llamada",
        "sla_days": 2,
        "steps_es": [
            "Agrupar los tickets del mes por causa raíz, no por síntoma.",
            "Escalar a producto si se repite en otras residencias.",
            "Dar una fecha concreta al cliente, aunque sea lejana.",
            "Confirmar cierre con la persona que abrió el ticket.",
        ],
        "steps_en": [
            "Group the month's tickets by root cause, not by symptom.",
            "Escalate to product if it recurs at other residences.",
            "Give the customer a concrete date, even a distant one.",
            "Confirm closure with whoever opened the ticket.",
        ],
        "whatsapp_es": "Hola {contact}, vi que abrieron {tickets} tickets este mes, varios por {module}. Antes de seguir respondiendo de a uno, prefiero que lo veamos juntos 15 minutos y lo arreglemos de raíz. ¿Te acomoda mañana?",
        "whatsapp_en": "Hi {contact}, I see {tickets} tickets opened this month, several about {module}. Rather than answering them one by one, I'd rather we spend 15 minutes and fix the root cause. Does tomorrow work?",
        "expected_es": "Sin tickets nuevos por la misma causa durante 30 días.",
        "expected_en": "No new tickets from the same cause for 30 days.",
    },
    "asegurar_renovacion": {
        "title_es": "Asegurar renovación",
        "title_en": "Secure the renewal",
        "objective_es": "Llegar a la renovación con evidencia de valor entregado.",
        "objective_en": "Arrive at renewal with evidence of value delivered.",
        "owner": "csm",
        "channel": "visita",
        "sla_days": 14,
        "steps_es": [
            "Preparar informe de uso y ahorro de tiempo del período.",
            "Cerrar antes cualquier ticket abierto.",
            "Reunión con quien firma, no solo con quien opera.",
            "Actualizar el negocio en Pipedrive.",
        ],
        "steps_en": [
            "Prepare a usage and time-saved report for the period.",
            "Close any open tickets first.",
            "Meet whoever signs, not only whoever operates.",
            "Update the deal in Pipedrive.",
        ],
        "whatsapp_es": "Hola {contact}, se viene la renovación de {residence} en {days} días. Preparé un resumen de cómo usaron la plataforma este año y dónde veo espacio para el próximo. ¿Nos juntamos 30 minutos a revisarlo?",
        "whatsapp_en": "Hi {contact}, the renewal for {residence} is {days} days away. I've put together a summary of how you used the platform this year and where I see room for next year. Shall we spend 30 minutes on it?",
        "expected_es": "Renovación firmada al menos 30 días antes del vencimiento.",
        "expected_en": "Renewal signed at least 30 days before expiry.",
    },
    "retomar_contacto": {
        "title_es": "Retomar contacto",
        "title_en": "Re-establish contact",
        "objective_es": "Recuperar la relación antes de que el silencio se vuelva distancia.",
        "objective_en": "Recover the relationship before silence becomes distance.",
        "owner": "csm",
        "channel": "whatsapp",
        "sla_days": 2,
        "steps_es": [
            "Revisar el historial antes de escribir, para no repetir preguntas.",
            "Mensaje breve, sin pedir nada a cambio.",
            "Si no responde en 72 h, llamar a recepción.",
        ],
        "steps_en": [
            "Review the history before writing, so you don't repeat questions.",
            "Short message, asking nothing in return.",
            "If no reply in 72h, call the front desk.",
        ],
        "whatsapp_es": "Hola {contact}, hace {days} días que no conversamos. ¿Cómo va todo en {residence}? Cualquier cosa que necesiten del sistema, me dices y lo vemos.",
        "whatsapp_en": "Hi {contact}, it's been {days} days since we last spoke. How is everything at {residence}? If there's anything you need from the system, just say and we'll sort it.",
        "expected_es": "Conversación activa y próxima revisión agendada.",
        "expected_en": "Live conversation and a next review scheduled.",
    },
    "explorar_expansion": {
        "title_es": "Explorar expansión",
        "title_en": "Explore expansion",
        "objective_es": "Acompañar el crecimiento de una residencia que ya está al límite de su plan.",
        "objective_en": "Support growth at a residence already at the limit of its plan.",
        "owner": "ventas",
        "channel": "llamada",
        "sla_days": 10,
        "steps_es": [
            "Confirmar ocupación real y licencias en uso.",
            "Cuantificar el uso por sobre lo contratado.",
            "Proponer plan superior con los módulos que ya piden.",
            "Crear el negocio en Pipedrive.",
        ],
        "steps_en": [
            "Confirm real occupancy and licences in use.",
            "Quantify usage above what is contracted.",
            "Propose the higher plan with the modules they already ask for.",
            "Create the deal in Pipedrive.",
        ],
        "whatsapp_es": "Hola {contact}, {residence} está usando la plataforma bastante por sobre lo que contrataron y las licencias quedaron cortas. ¿Vemos cómo dejarlo bien dimensionado para el próximo período?",
        "whatsapp_en": "Hi {contact}, {residence} is using the platform well above what you contracted and you've run short on licences. Shall we look at sizing it properly for the next period?",
        "expected_es": "Propuesta enviada y negocio creado en Pipedrive.",
        "expected_en": "Proposal sent and deal created in Pipedrive.",
    },
}


def get(key: str) -> dict | None:
    return PLAYBOOKS.get(key)
